name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "f271ba1d7dad40ff9394cf4c2905206a" },
  { binding = "SHARE", id = "ff3e620a6f0248289a6d501ff06e4a2c" }
]